# Generated by Django 4.2 on 2023-04-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0008_remove_fileupload_uname_alter_fileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('HSHD_NUM', models.IntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('L', models.CharField(max_length=10)),
                ('AGE_RANGE', models.CharField(max_length=100)),
                ('MARITAL', models.CharField(max_length=100)),
                ('INCOME_RANGE', models.CharField(max_length=100)),
                ('HOMEOWNER', models.CharField(max_length=100)),
                ('HSHD_COMPOSITION', models.CharField(max_length=100)),
                ('HH_SIZE', models.CharField(max_length=100)),
                ('CHILDREN', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PRODUCT_NUM', models.IntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('DEPARTMENT', models.CharField(max_length=100)),
                ('COMMODITY', models.CharField(max_length=100)),
                ('BRAND_TY', models.CharField(max_length=100)),
                ('NATURAL_ORGANIC_FLAG', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BASKET_NUM', models.IntegerField(blank=True, default=-1, null=True)),
                ('PURCHASE', models.DateField(auto_now_add=True)),
                ('SPEND', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('UNITS', models.IntegerField(blank=True, default=0, null=True)),
                ('STORE_R', models.CharField(max_length=100)),
                ('WEEK_NUM', models.IntegerField(blank=True, default=0, null=True)),
                ('YEAR', models.IntegerField(blank=True, default=2000, null=True)),
                ('HSHD_NUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment1.household')),
                ('PRODUCT_NUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment1.product')),
            ],
        ),
    ]
