# Generated by Django 4.2 on 2023-04-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0009_household_product_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='HSHD_NUM',
            field=models.IntegerField(blank=True, default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRODUCT_NUM',
            field=models.IntegerField(blank=True, default=1, primary_key=True, serialize=False),
        ),
    ]
