# Generated by Django 4.2 on 2023-04-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0013_alter_household_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='HH_SIZE',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
